{% set name = "ruamel.yaml.jinja2" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8449be29d9a157fa92d1648adc161d718e469f0d38a6b21e0eabb76fd5b3e663
  patches:
    # The package hasn't been maintained for 4 years and doesn't support py314.
    # Python 3.14 removed old AST node types. Simple aliasing fails because Constant uses '.value' attribute while old types used .s/.n.
    # The patch makes isinstance(node, Str) work AND handles attribute access correctly.
    # We patche setup.py with two changes:
    # 1. Imports Constant and aliases it to Str, Num, Bytes, NameConstant for Python 3.14.
    # 2. Adds early check in _convert() to return node.value for Constant instances.
    - py314-ast-compat.patch  # [py==314]

build:
  number: 1
  skip: true  # [py<37]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation
    - {{ PYTHON }} {{ RECIPE_DIR }}/rm_broken_file.py

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ruamel.yaml >=0.15.10

test:
  imports:
    - ruamel.yaml.jinja2
  requires:
    - pip
  commands:
    - pip check
    - python -c "from ruamel.yaml import YAML; YAML(typ='jinja2')"

about:
  home: https://sourceforge.net/projects/ruamel-yaml-jinja2/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: jinja2 pre and post-processor to update YAML
  description: |
    jinja2 templates for YAML files can normally not be loaded as YAML before
    rendering. This plugin allows pre and post-processing based on the
    round-trip processor.
  dev_url: https://sourceforge.net/p/ruamel-yaml-jinja2/code/ci/default/tree/
  doc_url: https://sourceforge.net/projects/ruamel-yaml-jinja2/

extra:
  recipe-maintainers:
    - marcelotrevisani
